name: 'mirror-images-action'
description: 'Mirror images to your account of hub.docker.com'

inputs:
  username:
    description: the account of docker.io
    required: true
  password:
    description: the password of the account
    requried: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
