name: Mirror images
on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mirror images to docker.io
      if: true
      uses: ./
      with:
        registry: docker.io
        group: kanzihuang
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Mirror images to swr.cn-north-1.myhuaweicloud.com
      if: false
      uses: ./
      with:
        registry: swr.cn-north-1.myhuaweicloud.com
        group: kanzihuang
        username: cn-north-1@${{ secrets.HUAWEIHUB_USERNAME }}
        password: ${{ secrets.HUAWEIHUB_TOKEN }}
    - name: Mirror images to swr.cn-north-4.myhuaweicloud.com
      if: false
      uses: ./
      with:
        registry: swr.cn-north-4.myhuaweicloud.com
        group: kanzihuang
        username: cn-north-4@${{ secrets.HUAWEIHUB_USERNAME }}
        password: ${{ secrets.HUAWEIHUB_TOKEN }}
