name: Mirror images to docker.io
on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mirror images
      uses: ./
      with:
        registry: swr.cn-north-4.myhuaweicloud.com
        group: kanzihuang
        username: ${{ secrets.HUAWEI_HUB_USERNAME }}
        password: ${{ secrets.HUAWEI_HUB_PASSWORD }}
