name: Mirror images to docker.io
on:
  push:
  workflow_dispatch:
env:
  DOCKER_HUB_REGISTRY: docker.io
  HUAWEI_HUB_REGISTRY: swr.cn-north-4.myhuaweicloud.com

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mirror images
      uses: ./
      with:
        registry: ${{ env.HUAWEI_HUB_REGISTRY }}
        group: kanzihuang
        username: ${{ secrets.HUAWEI_HUB_USERNAME }}
        password: ${{ secrets.HUAWEI_HUB_PASSWORD }}
